services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/upload_service
      - REDIS_URL=redis://redis:6379/0
      - GOOGLE_STORAGE_BUCKET=uploads-dev
      - ENVIRONMENT=development
      - GOOGLE_APPLICATION_CREDENTIALS=/app/service-account.json
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
      - ./service-account.json:/app/service-account.json:ro
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  worker:
    build: .
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/upload_service
      - REDIS_URL=redis://redis:6379/0
      - GOOGLE_STORAGE_BUCKET=uploads-dev
      - ENVIRONMENT=development
      - GOOGLE_APPLICATION_CREDENTIALS=/app/service-account.json
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
      - ./service-account.json:/app/service-account.json:ro
    command: celery -A api.v1.workers.celery_app worker --loglevel=info

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=upload_service
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"

volumes:
  postgres_data: